# General Setting

[log]
level  = "INFO"  # from Ruby Logger::LEVEL
rotate = "daily" # from Ruby Logger shift_age
# file = /path/to/logfile

[deliver]
min_interval = 60

[deliver.item]
merger = "PerItem"

[smtp]
host = 'localhost'
port = 25

[database.connect]
url = 'sqlite://tmp/poloxy.sqlite.db'

[message]
default_expire = 7200
default_snooze = 1800
